val_csv: "data/archive(1)/valid.csv"
image_root: "data/archive(1)/"
target: "Cardiomegaly"
sensitive_attr: "Sex"
batch_size: 32
pretrained_model: "models/vit_b_chexpert.pth"
prune_ratio: 0.1
beta: 0.3
